context.modules = [
    {
        name = libpipewire-module-echo-cancel
        args = {
            library.name = aec/libspa-aec-webrtc
            monitor.mode = true
            capture.props = {
                node.name = "svara-ec-capture"
                node.description = "Svara Echo-Cancel Capture"
            }
            source.props = {
                node.name = "svara-ec-source"
                node.description = "Svara Echo-Cancelled Source"
            }
        }
    }
]
